# 40-tools.zsh -- fzf, zoxide, yazi, starship.
#
# Everything here is guarded on the binary existing, so a bare clone of this
# repo on a machine without the full toolset still gives a working shell
# rather than a screenful of "command not found" at every prompt.

# ---------------------------------------------------------------------------
# fzf -- fuzzy finder
#
# Adds three keys to the shell:
#   Ctrl+R   search everything you have ever typed. Fuzzy: the letters just
#            have to appear in order, so `gitcom` finds `git commit --amend`.
#            This replaces the plain Ctrl+R that only matched substrings.
#   Ctrl+T   pick a file and paste its path onto the current line.
#   Alt+C    pick a directory and cd into it.
#
# Arch ships the integration as files under /usr/share/fzf. Sourcing them is
# cheaper than `source <(fzf --zsh)`, which forks a process at every startup.
# ---------------------------------------------------------------------------
if (( $+commands[fzf] )); then
    # Colours are palette-driven and live in a file theme-set renders.
    # FZF_DEFAULT_OPTS_FILE is fzf's own "read defaults from here" mechanism
    # (verified in `fzf --help`), so no giant option string in the env.
    export FZF_DEFAULT_OPTS_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/theme/fzf.conf"

    if (( $+commands[fd] )); then
        # fd instead of find: respects .gitignore, skips .git, and is fast
        # enough that Ctrl+T in a large tree stays instant.
        export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
        export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
        export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
    fi

    # Preview panes. {} is the highlighted entry.
    # --line-range caps how much of a large file gets rendered per keystroke.
    (( $+commands[bat] )) && \
        export FZF_CTRL_T_OPTS="--preview 'bat --color=always --style=numbers --line-range=:200 {}'"
    (( $+commands[eza] )) && \
        export FZF_ALT_C_OPTS="--preview 'eza --tree --level=2 --icons=always --color=always {}'"

    # No preview on history: the entry is the whole content already.
    export FZF_CTRL_R_OPTS='--no-preview'

    [[ -r /usr/share/fzf/key-bindings.zsh ]] && source /usr/share/fzf/key-bindings.zsh
    [[ -r /usr/share/fzf/completion.zsh   ]] && source /usr/share/fzf/completion.zsh
fi

# ---------------------------------------------------------------------------
# zoxide -- directory jumping
#
# Tracks the directories you visit and ranks them by how often and how
# recently. `z dot` jumps to ~/dotfiles from anywhere; `zi` opens an fzf list
# to pick from when the guess would be ambiguous.
#
# `cd` is left alone on purpose. zoxide can take it over with `--cmd cd`, but
# then cd's behaviour depends on invisible accumulated state, which is a bad
# trade when you are still learning what cd does.
# ---------------------------------------------------------------------------
(( $+commands[zoxide] )) && eval "$(zoxide init zsh)"

# ---------------------------------------------------------------------------
# yazi -- terminal file manager
#
# `yazi` alone browses and exits back where you started. `y` browses and
# leaves the shell IN the directory you ended up in, which is the reason to
# use it at all. It does that by having yazi write its final path to a temp
# file (--cwd-file, verified in `yazi --help`) and cd-ing there afterwards.
#
# Taken verbatim from the upstream Bash/Zsh wrapper in yazi's quick-start
# docs. One quirk worth knowing before anyone "fixes" it: the `read -r -d ""`
# returns exit status 1 under zsh, because it hits EOF without finding the
# delimiter -- but it still populates $cwd correctly. Verified directly. The
# trailing `|| builtin true` is what keeps that stray 1 from leaking out as
# the function's exit status.
# ---------------------------------------------------------------------------
if (( $+commands[yazi] )); then
    function y() {
        local tmp cwd; tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
        command yazi "$@" --cwd-file="$tmp"
        IFS= read -r -d '' cwd < "$tmp"
        [ "$cwd" != "$PWD" ] && [ -d "$cwd" ] && builtin cd -- "$cwd" || builtin true
        command rm -f -- "$tmp"
    }
fi

# ---------------------------------------------------------------------------
# starship -- the prompt
#
# Must be LAST of the tool initialisations: it installs precmd hooks, and
# anything sourced afterwards that also touches precmd can end up ordered
# ahead of it. ~/.config/starship.toml is generated by theme-set.
# ---------------------------------------------------------------------------
(( $+commands[starship] )) && eval "$(starship init zsh)"
