-- ~/.config/hypr/hyprland.lua
--
-- Thin loader. All real configuration lives in conf/*.lua.
-- Hyprland 0.56.2 -- config language is Lua (hyprlang deprecated since 0.55).
-- API reference for this exact version: /usr/share/hypr/stubs/hl.meta.lua
--
-- require() resolves against package.path, which Hyprland sets to include
-- ~/.config/hypr/?.lua -- verified empirically on this machine, so
-- require("conf.monitors") loads ~/.config/hypr/conf/monitors.lua
--
-- Order matters: theme before decorations (colors), autostart last.

require("conf.theme")        -- color palette (regenerated by `theme-set`)
require("conf.env")          -- environment variables
require("conf.monitors")     -- physical display layout
require("conf.workspaces")   -- workspace -> monitor binding
require("conf.input")        -- keyboard, touchpad, gestures
require("conf.misc")         -- compositor behaviour, swallowing, background
require("conf.decorations")  -- borders, gaps, rounding, blur
require("conf.animations")   -- curves + animation leaves
require("conf.rules")        -- window + layer rules
require("conf.binds")        -- keybindings
require("conf.autostart")    -- LAST: launches background processes
